<script src="assert.js"></script>
<script>
	function raError(){throw new RangeError("too large");}
	function tError(a){if(typeof a != "string")throw new TypeError("wrong type");}
	function uError(a){encodeURI(a);}
	function eError(){throw new EvalError("error while using eval");}
	function reError(){throw new ReferenceError("nothing to deference");}
	function sError(){throw new SyntaxError("spelling error");}
	function error(){throw new Error("general error");}
	function noError(){}
	
	//Custom Error
	function OsofemError(message){
		this.name = 'OsofemError';
		this.message = message || 'Default Message';
		this.stack = (new Error()).stack;
	}
	OsofemError.prototype = Object.create(Error.prototype);
	OsofemError.prototype.constructor = OsofemError;
	//function to throw custom error
	function customError(){throw new OsofemError("Too much sass :) ");}
	
	assertThrowError(raError, []/*empty arguments*/, RangeError, "RangeError is expected!");
	assertThrowError(tError, [1]/*number given instead of string*/, TypeError, "TypeError is expected!");
	assertThrowError(uError, ["\uD800"]/*invalid parameter given*/, URIError, "URIError is expected!");
	assertThrowError(eError, []/*empty arguments*/, EvalError, "EvalError is expected!");
	assertThrowError(reError, []/*empty arguments*/, ReferenceError, "ReferenceError is expected!");
	assertThrowError(sError, []/*empty arguments*/, SyntaxError, "SyntaxError is expected!");
	assertThrowError(error, []/*empty arguments*/, Error, "Error is expected!");
	
	assertThrowError(customError, []/*empty arguments*/, OsofemError, "OsofemError is expected!");
	
	assertThrowError(noError, []/*empty arguments*/, Error, "This should fail because no error was expected!");
</script>